AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 instance with OPC UA demo server'

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    ConstraintDescription: Must be a valid EC2 instance type

  ImageId:
    Type: String
    Default: ami-080ecf65f4d838a6e  # Amazon Linux 2023


Resources:

 # IAM Role para SSM
  OPCUAInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: opcua-server-ec2-ssm-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: opcua-server-ec2-ssm-role

  OPCUAInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref OPCUAInstanceRole

  OPCUASecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for OPC UA server
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 4840
          ToPort: 4840
          CidrIp: 0.0.0.0/0
          Description: OPC UA server port
      Tags:
        - Key: Name
          Value: opcua-server-security-group

  OPCUAServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      IamInstanceProfile: !Ref OPCUAInstanceProfile
      SecurityGroupIds:
        - !Ref OPCUASecurityGroup
      Tags:
        - Key: Name
          Value: opcua-server-demo

Outputs:
  InstanceId:
    Description: Instance ID of the OPC UA server
    Value: !Ref OPCUAServer
    
  PublicIP:
    Description: Public IP address of the OPC UA server
    Value: !GetAtt OPCUAServer.PublicIp
    
  OPCUAEndpoint:
    Description: OPC UA server endpoint URL
    Value: !Sub 'opc.tcp://${OPCUAServer.PublicIp}:4840/UA/DemoServer'
        
  CheckServerStatus:
    Description: Command to check server status (after SSH)
    Value: './check-opcua.sh'